import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {},
  client: {
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: z.string().min(1),
    NEXT_PUBLIC_ISSUE_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_USD_TOKEN_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_ALCHEMY_API_KEY: z.string().optional(),
    NEXT_PUBLIC_ZK_BACKEND_GENERATE_PROOF: z.string().optional(),
    NEXT_PUBLIC_ZK_BACKEND_GET_ACCESS_TOKEN: z.string().optional(),
    NEXT_PUBLIC_GITHUB_CLIENT_ID: z.string().optional(),
    NEXT_PUBLIC_SEPOLIA_RPC_URL: z.string().optional(),
    NEXT_PUBLIC_BUNDLER_RPC_URL: z.string().optional(),
    NEXT_PUBLIC_PAYMASTER_RPC_URL: z.string().optional(),
    NEXT_PUBLIC_APP_URL: z.string().optional(),
  },
  runtimeEnv: {
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
      process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
    NEXT_PUBLIC_ISSUE_ADDRESS: process.env.NEXT_PUBLIC_ISSUE_ADDRESS,
    NEXT_PUBLIC_USD_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_USD_TOKEN_ADDRESS,
    NEXT_PUBLIC_ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
    NEXT_PUBLIC_ZK_BACKEND_GENERATE_PROOF: process.env.NEXT_PUBLIC_ZK_BACKEND_GENERATE_PROOF,
    NEXT_PUBLIC_ZK_BACKEND_GET_ACCESS_TOKEN: process.env.NEXT_PUBLIC_ZK_BACKEND_GET_ACCESS_TOKEN,
    NEXT_PUBLIC_GITHUB_CLIENT_ID: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,
    NEXT_PUBLIC_SEPOLIA_RPC_URL: process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL,
    NEXT_PUBLIC_BUNDLER_RPC_URL: process.env.NEXT_PUBLIC_BUNDLER_RPC_URL,
    NEXT_PUBLIC_PAYMASTER_RPC_URL: process.env.NEXT_PUBLIC_PAYMASTER_RPC_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  },
});
